.

diff --git a/hackerEnv b/hackerEnv
--- a/hackerEnv
+++ b/hackerEnv
@@ -7,7 +7,7 @@
 
 #major.minor.patch
 #    0.X.X = beta
-VER='0.1.9'
+VER='0.2.0'
 full_path=$(realpath $0) #/opt/hackerEnv/hackerEnv.sh
 dir_path=$(dirname $full_path) #/opt/hackerEnv
 BLUE='\e[1;34m'
@@ -60,6 +60,22 @@ function updateOptWithVerbose {
   		echo -e "+ -- --=[hackerEnv is already the latest version."
   		echo ""
 	fi
+}
+function valid_ip()
+{
+    local  ip=$1
+    local  stat=1
+
+    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+        OIFS=$IFS
+        IFS='.'
+        ip=($ip)
+        IFS=$OIFS
+        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
+            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
+        stat=$?
+    fi
+    return $stat
 }
 function cleanning(){
 if [ -f $dir_path/online.txt ] && [ -f $dir_path/online.txt ]
@@ -824,17 +840,30 @@ fi
 ###############################################
 ###############################################
 
-if ! [[ $target =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
+if [ "$target" = "" ]
 then
-	echo -e "${RED}Invalid IP!${resetStyle}\n$(basename $0) -h, --help   Display help message 1."
-	exit
+    echo "No IP was provided "
+    exit
 fi
+    if [ "$target" != "" ]
+    then
+        for ip in $target
+        do
+            if valid_ip $ip
+            then
+                stat='good'
+            else
+                echo -e "${RED}Invalid IP: $ip ${resetStyle}\n$(basename $0) -h, --help   Display help message 1."
+                exit
+            fi
+        done
+    fi
 
-if ! [[ $subNetwork =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ $subNetwork -le 0 ]] && [[ $subNetwork -ge 30 ]] || ([ $subNetwork = "" ])
-then
-	echo -e "${RED}Invalid subnets!${resetStyle}\n$(basename $0) -h, --help   Display help message 2."
-	exit
-fi
+#if ! [[ $subNetwork =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ $subNetwork -le 0 ]] && [[ $subNetwork -ge 30 ]] || ([ $subNetwork = "" ])
+#then
+#	echo -e "${RED}Invalid subnets!${resetStyle}\n$(basename $0) -h, --help   Display help message 2."
+#	exit
+#fi
 
 ip a |grep -oP 'inet \K[^ ]+'| cut -f1-1 -d"/"|sed -n '2{p;q}' > $dir_path/urIp.txt
 ip="$(cat $dir_path/urIp.txt)"
